apiVersion: v1
kind: Service
metadata:
  name: shiny
  namespace: traffics
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: traffics
spec:
  ports:
  - port: 3838
    protocol: TCP
  selector:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: traffics

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shiny
  namespace: traffics
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-c4m
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: traffics
spec:
  rules:
  - host: traffics.codeformuenster.org
    http:
      paths:
      - backend:
          service:
            name: shiny
            port:
              number: 3838
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - traffics.codeformuenster.org
    secretName: traffics-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiny
  namespace: traffics
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: traffics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shiny
      app.kubernetes.io/component: webserver
      app.kubernetes.io/part-of: traffics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shiny
        app.kubernetes.io/component: webserver
        app.kubernetes.io/part-of: traffics
    spec:
      containers:
      - name: shiny
        image: codeformuenster/traffic-dynamics-shiny:v0.6.4
        ports:
        - containerPort: 3838
        resources:
          requests:
            memory: "200Mi"
            cpu: "640m"
