apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: c4m-crashes

resources:
- ../../base/namespace
- ./postgis.yaml
- ./shiny.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: crashfals
