apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: c4m-crashes

commonLabels:
  app.kubernetes.io/part-of: crashes

resources:
- ../../base/namespace
- ./postgis.yaml
- ./shiny.yaml
