apiVersion: v1
kind: Service
metadata:
  name: shiny
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
spec:
  ports:
  - port: 3838
  selector:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shiny-crashes
automountServiceAccountToken: false

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shiny
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-c4m
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
spec:
  rules:
  - host: crashes.codeformuenster.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shiny
            port:
              number: 3838
  tls:
  - hosts:
    - crashes.codeformuenster.org
    secretName: crashes-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiny
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shiny
      app.kubernetes.io/component: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shiny
        app.kubernetes.io/component: webserver
    spec:
      automountServiceAccountToken: false
      serviceAccountName: shiny-crashes
      securityContext:
        fsGroup: 998
      containers:
      - name: shiny
        image: quay.io/codeformuenster/crashes-shiny:v6.7.2
        resources:
          requests:
            memory: "350Mi"
            cpu: "640m"
        ports:
        - containerPort: 3838
        env:
        - name: TMPDIR
          value: /tmp/shiny
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 998
          runAsNonRoot: true
          runAsUser: 998
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: renviron-file
          mountPath: /srv/shiny-server/.Renviron
          subPath: .Renviron
        - name: shiny-tmp
          mountPath: /var/log/shiny-server
          subPath: log
        - name: shiny-tmp
          mountPath: /var/lib/shiny-server
          subPath: lib
        - name: shiny-tmp
          mountPath: /tmp
          subPath: tmp
      volumes:
      - name: renviron-file
        configMap:
          name: renviron
      - name: shiny-tmp
        emptyDir:
          medium: Memory
          sizeLimit: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renviron
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
data:
  .Renviron: |
    POSTGRES_HOST=postgis
