---
apiVersion: v1
kind: Service
metadata:
  name: shiny
  namespace: crashes
  labels:
    app.kubernetes.io/name: shiny
    # app.kubernetes.io/version: "4.9.9"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: crashes
spec:
  ports:
  - port: 3838
  selector:
    app.kubernetes.io/name: shiny
    # app.kubernetes.io/version: "4.9.9"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: crashes

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shiny
  namespace: crashes
  labels:
    app.kubernetes.io/name: shiny
    # app.kubernetes.io/version: "4.9.9"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: crashes
spec:
  rules:
  - host: crashes.codeformuenster.org
    http:
      paths:
      - path: /
        backend:
          serviceName: shiny
          servicePort: 3838
  tls:
  - hosts:
    - crashes.codeformuenster.org
    secretName: crashes-tls

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: crashes-tls
  namespace: crashes
  labels:
    app.kubernetes.io/name: shiny
    # app.kubernetes.io/version: "4.9.9"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: crashes
spec:
  secretName: crashes-tls
  commonName: crashes.codeformuenster.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiny
  namespace: crashes
  labels:
    app.kubernetes.io/name: shiny
    # app.kubernetes.io/version: "4.9.9"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: crashes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shiny
      # app.kubernetes.io/version: "4.9.9"
      app.kubernetes.io/component: webserver
      app.kubernetes.io/part-of: crashes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shiny
        # app.kubernetes.io/version: "4.9.9"
        app.kubernetes.io/component: webserver
        app.kubernetes.io/part-of: crashes
    spec:
      containers:
      - name: shiny
        image: quay.io/codeformuenster/crashes-shiny:4.9.9
        ports:
        - containerPort: 3838
