apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: meine-stadt-transparent
commonLabels:
  app.kubernetes.io/part-of: meine-stadt-transparent

resources:
# - ../../../kustomized/minio
# - ../../../kustomized/elasticsearch
# - ../../../kustomized/mariadb

- github.com/codeformuenster/kustomized//minio?ref=1e7ba4237e771b4281c0df468bd7177d3db15511
- github.com/codeformuenster/kustomized//elasticsearch?ref=1e7ba4237e771b4281c0df468bd7177d3db15511
- github.com/codeformuenster/kustomized//mariadb?ref=1e7ba4237e771b4281c0df468bd7177d3db15511

- ./meine-stadt-transparent.yaml
- ./nginx.yaml
- ./scraping.yaml
#- ./ingress.yaml

patchesStrategicMerge:
- ./elasticsearch_patch.yaml

configMapGenerator:
- name: nginx-config
  behavior: create
  files:
  - nginx.conf=./configs/nginx-http.conf
- name: mariadb-env-vars
  behavior: replace
  literals:
  - user=meine-stadt-transparent
  - database=meine-stadt-transparent

secretGenerator:
- name: minio
  behavior: replace
  envs:
  - ./secrets/minio.env
- name: mariadb-passwords
  behavior: replace
  envs:
  - ./secrets/mariadb.env
- name: elasticsearch-passwords
  behavior: create
  envs:
  - ./secrets/elasticsearch.env
- name: elasticsearch-certificates
  behavior: create
  files:
  - root-ca.pem=./secrets/certificates/elasticsearch-ca.crt
  - node.pem=./secrets/certificates/elasticsearch.crt
  - node-key.pem=./secrets/certificates/elasticsearch-pk8.key
- name: meine-stadt-transparent-secrets
  behavior: create
  envs:
  - ./secrets/meine-stadt-transparent.env


images:
- name: minio/minio
  newTag: RELEASE.2019-10-12T01-39-57Z
- name: mariadb
  newTag: 10.4.10
- name: konstin2/meine-stadt-transparent
  newName: quay.io/codeformuenster/meine-stadt-transparent
  newTag: container-image-0.1.0
