apiVersion: v1
kind: Service
metadata:
  name: meine-stadt-transparent
  labels:
    app.kubernetes.io/name: meine-stadt-transparent
    app.kubernetes.io/component: django
    app.kubernetes.io/part-of: meine-stadt-transparent
spec:
  ports:
  - port: 8000
  selector:
    app.kubernetes.io/name: meine-stadt-transparent
    app.kubernetes.io/component: django
    app.kubernetes.io/part-of: meine-stadt-transparent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meine-stadt-transparent
  labels:
    app.kubernetes.io/name: meine-stadt-transparent
    app.kubernetes.io/component: django
    app.kubernetes.io/part-of: meine-stadt-transparent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: meine-stadt-transparent
      app.kubernetes.io/component: django
      app.kubernetes.io/part-of: meine-stadt-transparent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meine-stadt-transparent
        app.kubernetes.io/component: django
        app.kubernetes.io/part-of: meine-stadt-transparent
    spec:
      initContainers:
      - name: django-migrate
        image: konstin2/meine-stadt-transparent:latest
        args:
          - ./manage.py
          - migrate
        env:
        - name: DEBUG
          value: "False"
        - name: REAL_HOST
          value: meine-stadt-transparent.codeformuenster.org
        - name: ELASTICSEARCH_URL
          value: "elasticsearch:9200"
        - name: MINIO_HOST
          value: "minio:9000"
        - name: STATIC_ROOT
          value: /static
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: database_url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: secret_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secret-key
      # - name: django-loaddata
      #   image: konstin2/meine-stadt-transparent:latest
      #   args:
      #     - ./manage.py
      #     - loaddata
      #     - mainapp/fixtures/initdata.json
      #   env:
      #   - name: DEBUG
      #     value: "False"
      #   - name: REAL_HOST
      #     value: meine-stadt-transparent.codeformuenster.org
      #   - name: ELASTICSEARCH_URL
      #     value: "elasticsearch:9200"
      #   - name: MINIO_HOST
      #     value: "minio:9000"
      #   - name: STATIC_ROOT
      #     value: /static
      #   - name: DATABASE_URL
      #     valueFrom:
      #       secretKeyRef:
      #         name: meine-stadt-transparent-secrets
      #         key: database_url
      #   - name: SECRET_KEY
      #     valueFrom:
      #       secretKeyRef:
      #         name: meine-stadt-transparent-secrets
      #         key: secret_key
      #   - name: MINIO_SECRET_KEY
      #     valueFrom:
      #       secretKeyRef:
      #         name: minio
      #         key: secret-key
      containers:
      - name: meine-stadt-transparent
        image: konstin2/meine-stadt-transparent:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: REAL_HOST
          value: meine-stadt-transparent.codeformuenster.org
        - name: ELASTICSEARCH_URL
          value: "elasticsearch:9200"
        - name: MINIO_HOST
          value: "minio:9000"
        - name: STATIC_ROOT
          value: /static
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: database_url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: secret_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secret-key
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: access-key
