apiVersion: v1
kind: Service
metadata:
  name: meine-stadt-transparent
  labels:
    app.kubernetes.io/name: meine-stadt-transparent
    app.kubernetes.io/component: django
    app.kubernetes.io/part-of: meine-stadt-transparent
spec:
  ports:
  - port: 8000
  selector:
    app.kubernetes.io/name: meine-stadt-transparent
    app.kubernetes.io/component: django
    app.kubernetes.io/part-of: meine-stadt-transparent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meine-stadt-transparent
  labels:
    app.kubernetes.io/name: meine-stadt-transparent
    app.kubernetes.io/component: django
    app.kubernetes.io/part-of: meine-stadt-transparent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: meine-stadt-transparent
      app.kubernetes.io/component: django
      app.kubernetes.io/part-of: meine-stadt-transparent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meine-stadt-transparent
        app.kubernetes.io/component: django
        app.kubernetes.io/part-of: meine-stadt-transparent
    spec:
      volumes:
      - name: dotenv
        configMap:
          name: meine-stadt-transparent-dot-env
      initContainers:
      - name: django-migrate
        image: konstin2/meine-stadt-transparent:latest
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -c
        args:
        - 'set -e &&
          /app/.venv/bin/python /app/manage.py migrate &&
          /app/.venv/bin/python /app/manage.py search_index --create || true'
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: database_url
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: sentry_dsn
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: secret_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secret-key
        volumeMounts:
        - name: dotenv
          mountPath: /app/.env
          subPath: .env
      containers:
      - name: meine-stadt-transparent
        image: konstin2/meine-stadt-transparent:v0.2.0
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: dotenv
          mountPath: /app/.env
          subPath: .env
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: database_url
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: sentry_dsn
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: meine-stadt-transparent-secrets
              key: secret_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: secret-key
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: access-key
