apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: meine-stadt-transparent
spec:
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: meine-stadt-transparent

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meine-stadt-transparent
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: meine-stadt-transparent
spec:
  rules:
  - host: meine-stadt-transparent.codeformuenster.org
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
  tls:
  - hosts:
    - meine-stadt-transparent.codeformuenster.org
    secretName: meine-stadt-transparent-tls

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: meine-stadt-transparent-tls
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: meine-stadt-transparent
spec:
  secretName: meine-stadt-transparent-tls
  commonName: meine-stadt-transparent.codeformuenster.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/part-of: meine-stadt-transparent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/component: nginx
      app.kubernetes.io/part-of: meine-stadt-transparent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/component: nginx
        app.kubernetes.io/part-of: meine-stadt-transparent
    spec:
      volumes:
      - name: static-files-volume
        emptyDir: {}
      - name: nginxconfig
        configMap:
          name: nginx-config
      initContainers:
      - name: copy-static
        image: konstin2/meine-stadt-transparent:latest
        command:
          - cp
          - -r
          - /static
          - /static-files
        volumeMounts:
        - mountPath: /static-files
          name: static-files-volume
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        volumeMounts:
        - mountPath: /static
          name: static-files-volume
          subPath: static
        - mountPath: /etc/nginx/conf.d/meine-stadt-transparent.conf
          name: nginxconfig
          subPath: nginx.conf
