apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sessionnet-scraper
  labels:
    app.kubernetes.io/name: sessionnet-scraper-cronjob
    app.kubernetes.io/component: sessionnet-scraper
    app.kubernetes.io/part-of: meine-stadt-transparent


#docker run --rm --volume /root/scrape-session/ratsinformationssysteme:/app/ratsinformationssysteme --volume /root/scrape-session/cache/:/app/cache/ --volume /root/s    crape-session/json/:/app/json/ konstin2/scrape-session download Münster
#docker run --rm --volume /root/scrape-session/ratsinformationssysteme:/app/ratsinformationssysteme --volume /root/scrape-session/cache/:/app/cache/ --volume /root/s    crape-session/json/:/app/json/ konstin2/scrape-session download Münster --skip-existing
#docker run --rm --volume /root/scrape-session/ratsinformationssysteme:/app/ratsinformationssysteme --volume /root/scrape-session/cache/:/app/cache/ --volume /root/s    crape-session/json/:/app/json/ konstin2/scrape-session parse Karlsruhe Magdeburg Moers Münster Oelde Wuppertal

spec:
  schedule: "5 4 * * *"
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: scraping-data-volume
            emptyDir: {}
          initContainers:
          - name: download-and-parse
            image: quay.io/geraldpape/k2zw4wag4phikk8ioepa5gzhg0o5dhba0ayken9a8lu4g365c1rjan9n8yv5:a3asaut2po6e15ans6ft
            command:
            - /bin/bash
            - -c
            args:
            - 'set -e &&
              /app/.venv/bin/python -m scrape_session.main download Münster --skip-existing &&
              sleep 60 &&
              /app/.venv/bin/python -m scrape_session.main download Münster --skip-existing &&
              sleep 60 &&
              /app/.venv/bin/python -m scrape_session.main download Münster --skip-existing &&
              /app/.venv/bin/python -m scrape_session.main parse Münster'
            volumeMounts:
            - mountPath: /app/storage
              name: scraping-data-volume
          containers:
          - name: import-scraped-json
            image: konstin2/meine-stadt-transparent:latest
            command:
            - /bin/bash
            - -c
            args:
            - 'set -e &&
              /app/.venv/bin/python /app/manage.py import_json /app/storage/json/Münster.json'
            volumeMounts:
            - mountPath: /app/storage
              name: scraping-data-volume
            env:
            - name: DEBUG
              value: "False"
            - name: REAL_HOST
              value: meine-stadt-transparent.codeformuenster.org
            - name: ELASTICSEARCH_URL
              value: "elasticsearch:9200"
            - name: MINIO_HOST
              value: "minio:9000"
            - name: STATIC_ROOT
              value: /static
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: meine-stadt-transparent-secrets
                  key: database_url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: meine-stadt-transparent-secrets
                  key: secret_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secret-key
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: access-key
