apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sessionnet-scraper
  labels:
    app.kubernetes.io/name: sessionnet-scraper-cronjob
    app.kubernetes.io/component: sessionnet-scraper
    app.kubernetes.io/part-of: meine-stadt-transparent
spec:
  schedule: "5 4 * * *"
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: scraping-data-volume
            emptyDir: {}
          initContainers:
          - name: download-and-parse
            image: konstin2/scrape-session:latest
            imagePullPolicy: Always
            command:
            - /bin/bash
            - -c
            args:
            - 'set -e &&
              /app/.venv/bin/python -m scrape_session.main scrape Münster'
            volumeMounts:
            - mountPath: /app/storage
              name: scraping-data-volume
          containers:
          - name: import-scraped-json
            image: konstin2/meine-stadt-transparent:latest
            imagePullPolicy: Always
            command:
            - /bin/bash
            - -c
            args:
            - 'set -e &&
              /app/.venv/bin/python /app/manage.py import_json --allow-shrinkage /app/storage/json/Münster.json &&
              /app/.venv/bin/python /app/manage.py search_index --populate'
            volumeMounts:
            - mountPath: /app/storage
              name: scraping-data-volume
            env:
            - name: DEBUG
              value: "False"
            - name: REAL_HOST
              value: meine-stadt-transparent.codeformuenster.org
            - name: ELASTICSEARCH_URL
              value: "elasticsearch-master:9200"
            - name: MINIO_HOST
              value: "minio:9000"
            - name: STATIC_ROOT
              value: /static
            - name: ELASTICSEARCH_QUERYSET_PAGINATION
              value: "5"
            - name: ELASTICSEARCH_TIMEOUT
              value: "30"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: meine-stadt-transparent-secrets
                  key: database_url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: meine-stadt-transparent-secrets
                  key: secret_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secret-key
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: access-key
          imagePullSecrets:
          - name: regcred
