apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kinto-test
  
bases:
- ../base
resources:
- namespace.yaml
patchesStrategicMerge:
- kinto-config_patch.yaml
- kinto-ingress_patch.yaml
# - postgresql-secret_patch.yaml
- postgres-volume_patch.yaml
