kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
spec:
  ports:
  - name: metrics
    port: 10254
    targetPort: metrics

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: null
        prometheus.io/scrape: null
    spec:
      containers:
      - name: nginx-ingress-controller
        ports:
        - name: metrics
          containerPort: 10254
