apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nominatim
spec:
  rules:
  - host: nominatim.codeformuenster.org
    http:
      paths:
      - backend:
          serviceName: nominatim
          servicePort: api
  tls:
  - secretName: nominatim-tls
    hosts:
    - nominatim.codeformuenster.org

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nominatim
spec:
  commonName: nominatim.codeformuenster.org
