##---
# Source: cert-manager/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager-cert-manager
  labels:
    app: cert-manager
    chart: cert-manager-0.2.4
    release: cert-manager
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cert-manager
        release: cert-manager
    spec:
      serviceAccountName: cert-manager-cert-manager
      containers:
        - name: cert-manager
          image: "quay.io/jetstack/cert-manager-controller:v0.2.3"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            
        - name: ingress-shim
          image: "quay.io/jetstack/cert-manager-ingress-shim:v0.2.3"
          imagePullPolicy: Always
          args:
            - --default-issuer-name=letsencrypt
            - --default-issuer-kind=ClusterIssuer
            
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            
