apiVersion: v1
kind: Secret
metadata:
    name: backend-api
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:bQlX8aXXbVVcbKFe/Jg=,iv:fl7Dgl7JkduwWitSI+YOetPYCyZNOC8tYicgURszW8A=,tag:MNNDsfvygUfmrMKiON5tbQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:TnmG1Q==,iv:GGrq/Yt1L6qdYYpCDGzk/imKKWKyKaj9KqQG/5AHCo4=,tag:H+i35jT/xU3SzrGNnnxTgw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:z7/PehJnYWpI+MFq0Rgv+PaD,iv:x1zfVi6Uke3DgW4tc1elEz8gGcboa2PaefozMdNycrc=,tag:cJxBuZiCs26lakhGhuxDJw==,type:str]
    DB_USER: ENC[AES256_GCM,data:dd7p7CXluQ/2kyaGP8fHeDOY,iv:AKE22aaCKhnSA47X4whNr5jsRQ1kXz0yVrvKJ8lHp30=,tag:SfPln/B/AN4gzxmjsICmLg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:kMDF71Y7lVModpFvZSjE6M55QMG/pEfkDAYfz2j3XILAGX6HbuJoNfXlpTxjoNL2VvVVjG8mHWFpZXt9dWYEag==,iv:/TiYi0vRy6TLH8LLhf0lu9kQidKHlJIvnnrRff/19zg=,tag:ewwdULxFi1+yB2uukPrzpw==,type:str]
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:noTgJ/NUnHUprBtxyUkYOO6RDsejs0kayWJQta5iz/V4ngDA5d06vxQ7xhWCi5F1A3E=,iv:Hmk9Mk6Wgll64Lded532y6CtmFF0o5ycEmsseZ4+VLY=,tag:tyHccLXA48QEvshDVU0x8w==,type:str]
    MUENSTERLAND_API_TOKEN: ENC[AES256_GCM,data:zclSA5Fq5yKw5zo9Y+rZfDQEg35VxdqUtzcvbB5uFxk=,iv:tDnSX/RVGsLgoCcmxzTae17CnW3HK4PVqD9XdIC3GoQ=,tag:1e2T4OhbJnlIpK3ZdDBF/Q==,type:str]
    DATENPORTAL_USER: ENC[AES256_GCM,data:0QrU59/3/YuDvlUQzXA=,iv:nPfj/D2raXo54a7kXdn4arS0/aqVMKeGjUSjUN57SMw=,tag:OCPKmqX/4kgQ18SHzfJZMQ==,type:str]
    DATENPORTAL_PASSWORD: ENC[AES256_GCM,data:FjmFsx80CKlr,iv:gV04RUl19IXk6Z4jMLp6OYzPeo3Kq/JxkB4cD2v0XPw=,tag:HKiVol6/LSH6ksgWMfusbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pj38nygg5qvcd6xqwdrn5cd8q0l4f2jvnql5dr3f22jhr29sw98qktj628
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROWtnNU9KQ0xpMU8vQlFq
            d2Z3eUpJQTdhdWpOZEU4blRhYWpxK2Y2b2hjCldyM3FTaU9Va0pOTmhSc0ZsNEJ6
            OG9uN1VoR1VMS2licjhNaTBuL3F1WkUKLS0tIC9TMTl6eDhpUEY0eVhhR3hOeVBj
            OGVFUW9SVC9ZTDVGaVljZEtucmNxQ2cKNuLxs5UUcZgofAb1pTTPvIPO7U3fkZ5n
            4dYePtbA9xkBqE1n/gjQN/HM6D5kKpRCfxZ65VuB3qerxN0fC4582g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-07T20:06:54Z"
    mac: ENC[AES256_GCM,data:nQazrsYCN08b4Ikpqe/zkuzYk96+rM3O2aLWPE5x2AjdwY0dKavYiBPqM3DHQEa3yTcYNjWG4+FgpZNTBLZc28YzOjDzh9yMeczNoI/G3/Byxt/GD2FZ78CW+HC2mmhosry7+A0kGkDnk60/zCt1znxzMAJo/n/zfvE9Kh9G5Iw=,iv:s75bs13OQgACXe6kBS4QRPW3XKqFG86RIuGjXDnzQQQ=,tag:SQEYcDISMQRhTeQoVG2Jrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
