apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
commonLabels:
  app.kubernetes.io/part-of: cert-manager

resources:
- ./cert-manager.yaml
- ./servicemonitor.yaml