apiVersion: v1
kind: Service
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
    release: cert-manager
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9402
    targetPort: 9402
  selector:
    app: cert-manager
    app.kubernetes.io/name: cert-manager

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  endpoints:
  - port: metrics
    # interval: 30s
    # honorLabels: true
  namespaceSelector:
    matchNames:
    - cert-manager
  selector:
    matchLabels:
      app: cert-manager
      app.kubernetes.io/name: cert-manager