apiVersion: v1
kind: Service
metadata:
  name: mosmix
  namespace: mosmix
  labels:
    app: mosmix
spec:
  ports:
  - name: api
    port: 3000
    targetPort: 3000
    # targetPort: api
    # protocol: TCP
  selector:
    app: mosmix
