apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-data
  namespace: mosmix
spec:
  storageClassName: local-ssd-normal-resilience
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20G
