apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: processor-s
  namespace: mosmix
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: processor-filecheck-s
            image: quay.io/codeformuenster/mosmix-processor:v20180717-1
            command: ["./mosmix-check", "-interval=10s", "mosmix_s"]
            resources:
              limits:
                memory: "2048Mi"
                cpu: "3000m"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true
          containers:
          - name: mosmix-processor-s
            image: quay.io/codeformuenster/mosmix-processor:v20180717-1
            command: ["./mosmix-processor"]
            args: ["-db=postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgis?sslmode=disable", "mosmix_s"]
            env:
            - name: POSTGRES_USER
              value: mosmix
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis
                  key: postgres-password
            resources:
              requests:
                memory: "1024Mi"
                cpu: "1500m"
              limits:
                memory: "2048Mi"
                cpu: "3000m"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true
            volumeMounts:
            - mountPath: /tmp
              name: temp-download
          volumes:
          - name: temp-download
            emptyDir:
              medium: Memory
