## This file exists because the helm chart https://github.com/RemiKalbe/overpass-api-helm-chart
## specifies a initialization Job as a helm hook which uses the ServiceAccount below.
## The ServiceAccount isn't part of the hooks though
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: overpass-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: overpass-api
    app.kubernetes.io/version: 0.7.62
    helm.sh/chart: overpass-api-0.3.4
    helm.toolkit.fluxcd.io/name: overpass-api
    helm.toolkit.fluxcd.io/namespace: overpass
  name: overpass-api-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: overpass-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: overpass-api
    app.kubernetes.io/version: 0.7.62
    helm.sh/chart: overpass-api-0.3.4
    helm.toolkit.fluxcd.io/name: overpass-api
    helm.toolkit.fluxcd.io/namespace: overpass
  name: overpass-api-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: overpass-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: overpass-api
    app.kubernetes.io/version: 0.7.62
    helm.sh/chart: overpass-api-0.3.4
    helm.toolkit.fluxcd.io/name: overpass-api
    helm.toolkit.fluxcd.io/namespace: overpass
  name: overpass-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: overpass-api-role
subjects:
- kind: ServiceAccount
  name: overpass-api-sa

