apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: overpass-api
    app.kubernetes.io/name: overpass-api
    app.kubernetes.io/version: 0.7.62
  name: overpass-api-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
  volumeMode: Filesystem
