apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
rules:
- apiGroups: ["certmanager.k8s.io"]
  resources: ["certificates", "issuers", "clusterissuers"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets", "events", "endpoints", "services", "pods"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager
  namespace: cert-manager  
  labels:
    app: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager
subjects:
- name: cert-manager
  namespace: cert-manager
  kind: ServiceAccount
