apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: admin@codeformuenster.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cfm-issuer-account-key

    # Configure the challenge solvers.
    solvers:
    # An empty selector will 'match' all Certificate resources that
    # reference this Issuer.
    - selector: {}
      http01:
        ingress:
          class: nginx
