apiVersion: v1
kind: Service
metadata:
  name: crashes
spec:
  ports:
  - port: 3838
    protocol: TCP
    name: shiny
    targetPort: shiny
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crashes
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: crashes.codeformuenster.org
    http:
      paths:
      - backend:
          service:
            name: crashes
            port:
              name: shiny
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - crashes.codeformuenster.org
    secretName: crashes-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashes
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - name: shiny
        image: quay.io/codeformuenster/crashes-shiny:v6.7.2
        ports:
        - containerPort: 3838
          name: shiny
        securityContext:
          runAsUser: 998
          runAsGroup: 998
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: renviron-file
          mountPath: /srv/shiny-server/.Renviron
          subPath: .Renviron
        - name: cache-volume
          mountPath: /var/lib/shiny-server
      volumes:
      - name: renviron-file
        configMap:
          name: renviron
      - emptyDir: {}
        name: cache-volume
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renviron
data:
  .Renviron: |
    SHINY_LOG_STDERR=1
    POSTGRES_HOST=postgis
    FATHOM_SITEID=ESCBJ
