apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-auth
  labels:
    app: kibana-auth
    stack: logging
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: kibana.codeformuenster.org
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: oauth2-proxy
          servicePort: 4180
  tls:
  - secretName: kibana-tls
    hosts:
    - kibana.codeformuenster.org
