- job_name: 'blackbox'
  metrics_path: /probe
  scrape_interval: 1m
  static_configs:
  - targets:                         # targets to be tested by the blackbox exporter
    - https://crashes.codeformuenster.org
    - https://fathom.codeformuenster.org
    - https://keycloak.codeformuenster.org
    - https://grafana.codeformuenster.org
    - https://traffics.codeformuenster.org
    - https://editor-data-helpers-verkehrsunfaelle.codeformuenster.org
    - https://kinto-verkehrsunfaelle.codeformuenster.org
  relabel_configs:
  - source_labels: [__address__]     # set param 'target' to the original target
    regex: (.*)
    target_label: __param_target
    replacement: ${1}
  - source_labels: [__param_target]  # set label 'instance' to it as well
    regex: (.*)
    target_label: instance
    replacement: ${1}
  - source_labels: []                # set __address__ to the blackbox exporter
    regex: .*
    target_label: __address__
    replacement: blackbox-exporter:9115

  # # blackbox-exporter 
  # # from gerald
  # 
  # - job_name: 'blackbox'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]  # Look for a HTTP 200 response.
  #   static_configs:
  #     - targets:
  #       - http://codeformuenster.org
  #       - https://mein-ms.de
  #       - https://www.mein-ms.de
  #       - https://elasticsearch.codeformuenster.org
  #       - https://elasticsearch.codeformuenster.org/_search
  #       - https://traffics.codeformuenster.org
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox-exporter:9115  # Blackbox exporter.


# ICMP Pings with the Blackbox exporter
#   https://www.robustperception.io/icmp-pings-with-the-blackbox-exporter
