apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traffics

resources:
- ./0-namespace.yaml
- ./traffics.yaml

commonLabels:
  app.kubernetes.io/name: traffics
  app.kubernetes.io/component: shiny
  app.kubernetes.io/part-of: traffics
