kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: klima-api
  namespace: klima-api
  labels:
    app: klima-api
spec:
  replicas: 1
  template:
    metadata:
      name: klima-api
      labels:
        app: klima-api
    spec:
      containers:
      - name: klima-api
        image: codeformuenster/unims-kli-api:0.1.3
        env:
          - name: KLI_PROPERTIES
            value: TIMESTAMP,TIMESTAMP_UTC,RECORD,AirTC_Avg,SW_in_Avg,WS_ms_S_WVT,WindDir_D1_WVT,WindDir_SD1_WVT,WS_Gust_Max,RH_Avg,BP_kPa_Avg,Rain_Tot,BiralVisInst_Avg,WeatherCode00_Tot,WeatherCode04_Tot,WeatherCode30_Tot,WeatherCode40_Tot,WeatherCode50_Tot,WeatherCode60_Tot,WeatherCode70_Tot
        ports:
        - name: api
          containerPort: 8080
