apiVersion: v1
kind: Service
metadata:
  name: shiny
  namespace: traffics
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: traffics
spec:
  ports:
  - port: 3838
    protocol: TCP
  selector:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: traffics

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shiny
  namespace: traffics
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: traffics
spec:
  rules:
  - host: traffics.codeformuenster.org
    http:
      paths:
      - backend:
          service:
            name: shiny
            port:
              number: 3838
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - traffics.codeformuenster.org
    secretName: traffics-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shiny-traffics
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiny
  namespace: traffics
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: traffics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shiny
      app.kubernetes.io/component: webserver
      app.kubernetes.io/part-of: traffics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shiny
        app.kubernetes.io/component: webserver
        app.kubernetes.io/part-of: traffics
    spec:
      serviceAccountName: shiny-traffics
      containers:
      - name: shiny
        image: codeformuenster/traffic-dynamics-shiny:v0.6.4
        ports:
        - containerPort: 3838
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 998
          runAsNonRoot: true
          runAsUser: 998
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "1024Mi"
            cpu: "640m"
        volumeMounts:
        - name: renviron-file
          mountPath: /srv/shiny-server/.Renviron
          subPath: .Renviron
        - name: varlogshinyserver
          mountPath: /var/log/shiny-server
        - name: varlibshinyserver
          mountPath: /var/lib/shiny-server
      volumes:
      - name: renviron-file
        configMap:
          name: renviron
      - name: varlogshinyserver
        emptyDir:
          sizeLimit: 100Mi
      - name: varlibshinyserver
        emptyDir:
          sizeLimit: 100Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renviron
  namespace: traffics
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: traffics
data:
  .Renviron: |
    FATHOM_SITEID=UFRTE
