apiVersion: v1
kind: Service
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: prometheus-operator
    apps.kubernetes.io/version: v0.30.0
  name: prometheus-operator
  namespace: kube-prometheus
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: prometheus-operator
