apiVersion: helm-template.webwur.st/v1alpha2
kind: HelmTemplate
metadata:
  name: nextcloud-test
  namespace: nextcloud-test
chart:
  repository: https://nextcloud.github.io/helm/
  name: nextcloud
  version: 2.2.0
localCache: true

# valueFiles: []
values:

  nextcloud:
    host: nextcloud-test.lan
    username: admin
    password: password

    # # Trigger update if custom command is used (?)
    # update: 0

    # # https://github.com/nextcloud/helm/tree/master/charts/nextcloud#multiple-configphp-file
    configs:
      # set ips of ingress-controllers?
      # updating this results in the error below
      reverse_proxy.php: |-
        <?php
        $CONFIG = array (
          'trusted_proxies'   => ['192.168.8.143', '172.18.0.2'],
          'overwriteprotocol' => 'https',
        );
      # > ERROR It looks like you are trying to reinstall your Nextcloud. However the file CAN_INSTALL is missing from your config directory. Please create the file CAN_INSTALL in your config folder to continue.
      # (don't use this)
      # CAN_INSTALL: ""
        
      # <?php
      # $CONFIG = array (
      #   'trusted_proxies'   => ['10.0.0.1'],
      #   'overwritehost'     => 'ssl-proxy.tld',
      #   'overwriteprotocol' => 'https',
      #   'overwritewebroot'  => '/domain.tld/nextcloud',
      #   'overwritecondaddr' => '^10\.0\.0\.1$',
      # );


  persistence:
    enabled: false
    # size: 8Gi

  cronjob.enabled: true

  ingress:
    # for nextcloud.host
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 4G
      # nginx.ingress.kubernetes.io/ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/secure-backends: "true"
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # cert-manager.io/cluster-issuer: "letsencrypt-prd"
    # tls:
    # - secretName: nextcloud-cert
    #   hosts:
    #   - nc.xxx.com

    # 'forwarded-for-headers' =>
    # array (
    # 0 => 'X-Forwarded-For',
    # 1 => 'HTTP_X_FORWARDED_FOR'
    # ),

    # The client IP address will be set based on the use of PROXY protocol or from the X-Forwarded-For header value when use-forwarded-headers is enabled.


  metrics:
    enabled: true

  # nextcloud.mail.enabled: false

  # internalDatabase.enabled: false
  # ^v- not the same?
  internalDatabase:
    enabled: false

  # https://github.com/helm/charts/tree/master/stable/mariadb#parameters
  mariadb:
    enabled: true

    replication:
      enabled: false

    # rootUser.password: secretpassword
    db:
      name: nextcloud
      user: nextcloud
      password: xxxx

    master.persistence:
      enabled: false
      # size: 8Gi
    # slave.persistence:
    #   enabled: false
    #   # size: 8Gi

  redis:
    enabled: false
