apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crashes
commonLabels:
  app.kubernetes.io/part-of: crashes

resources:
- ./postgis.yaml
- ./shiny.yaml

images:
- name: quay.io/codeformuenster/crashes-shiny
  newTag: v6.6.1
- name: quay.io/codeformuenster/verkehrsunfaelle
  newTag: 2019-06-06

# inventory:
#   type: ConfigMap
#   configMap:
#     name: prune-crashes
#     # namespace: crashes
