apiVersion: v1
kind: Service
metadata:
  name: shiny
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
spec:
  ports:
  - port: 3838
  selector:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shiny
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
spec:
  rules:
  - host: crashes.codeformuenster.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shiny
            port:
              number: 3838
  tls:
  - hosts:
    - crashes.codeformuenster.org
    secretName: crashes-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiny
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shiny
      app.kubernetes.io/component: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shiny
        app.kubernetes.io/component: webserver
    spec:
      containers:
      - name: shiny
        image: quay.io/codeformuenster/crashes-shiny:4.9.9
        ports:
        - containerPort: 3838
        volumeMounts:
        - name: renviron-file
          mountPath: /srv/shiny-server/.Renviron
          subPath: .Renviron
      volumes:
      - name: renviron-file
        configMap:
          name: renviron
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renviron
  labels:
    app.kubernetes.io/name: shiny
    app.kubernetes.io/component: webserver
data:
  .Renviron: |
    POSTGRES_HOST=postgis
    FATHOM_SITEID=ESCBJ
