apiVersion: v1
kind: Service
metadata:
  name: fileserver
  labels:
    app.kubernetes.io/name: swms-busradar-gtfs-realtime-fileserver
    app.kubernetes.io/component: fileserver
    app.kubernetes.io/part-of: swms-busradar-gtfs-realtime
spec:
  ports:
  - port: 2015
    protocol: TCP
    name: caddy
    targetPort: caddy
  selector:
    app.kubernetes.io/name: swms-busradar-gtfs-realtime-fileserver
    app.kubernetes.io/component: fileserver
    app.kubernetes.io/part-of: swms-busradar-gtfs-realtime

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileserver
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app.kubernetes.io/name: swms-busradar-gtfs-realtime-fileserver
    app.kubernetes.io/component: fileserver
    app.kubernetes.io/part-of: swms-busradar-gtfs-realtime
spec:
  rules:
  - host: gtfs-realtime.kube.vsh.codeformuenster.org
    http:
      paths:
      - backend:
          service:
            name: fileserver
            port:
              name: caddy
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - gtfs-realtime.kube.vsh.codeformuenster.org
    secretName: fileserver-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileserver
  labels:
    app.kubernetes.io/name: swms-busradar-gtfs-realtime-fileserver
    app.kubernetes.io/component: fileserver
    app.kubernetes.io/part-of: swms-busradar-gtfs-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: swms-busradar-gtfs-realtime-fileserver
      app.kubernetes.io/component: fileserver
      app.kubernetes.io/part-of: swms-busradar-gtfs-realtime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swms-busradar-gtfs-realtime-fileserver
        app.kubernetes.io/component: fileserver
        app.kubernetes.io/part-of: swms-busradar-gtfs-realtime
    spec:
      containers:
      - name: swms-busradar-gtfs-realtime-fileserver
        image: abiosoft/caddy:1.0.3-no-stats
        ports:
        - containerPort: 2015
          name: caddy
        volumeMounts:
        - name: caddyfile
          mountPath: /etc/Caddyfile
          subPath: Caddyfile
        - name: realtime-feed-volume
          mountPath: /srv
          readOnly: true
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
      - name: realtime-feed-volume
        persistentVolumeClaim:
          claimName: swms-busradar-gtfs-realtime-volume

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  labels:
    app.kubernetes.io/name: swms-busradar-gtfs-realtime-fileserver
    app.kubernetes.io/component: fileserver
    app.kubernetes.io/part-of: swms-busradar-gtfs-realtime
data:
  Caddyfile: |
    0.0.0.0
    root /srv
    gzip
    log stdout
    errors stdout
