apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
bases:
- ./upstream/cloud-generic
- ./upstream/cluster-wide
patchesStrategicMerge:
- ./patches/hostNetwork.yaml
- ./patches/scale.yaml
