apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-scraper-flow-test2
commonLabels:
  app.kubernetes.io/part-of: argo

resources:
# argo workflow
- github.com/argoproj/argo//manifests/namespace-install?ref=v2.4.2
# - github.com/codeformuenster/kustomized//minio?ref=5bac644696662fc2e6d9dd2b281d8362cc0cfeb8
- ./minio

# argo events
- github.com/argoproj/argo-events//hack/k8s/manifests?ref=v0.10
- ./webhook-gateway.yaml
- ./workflow-ingress.yaml
- ./workflows

patches:
- ./controller-configmap-patches.yaml
# - ./minio

images:
- name: argoproj/argoui
  newTag: v2.4.2
- name: argoproj/workflow-controller
  newTag: v2.4.2
- name: argoproj/gateway-controller
  newTag: v0.10
- name: argoproj/sensor-controller
  newTag: v0.10
- name: argoproj/gateway-client
  newTag: v0.10
- name: argoproj/webhook-gateway
  newTag: v0.10
- name: minio/minio
  newTag: RELEASE.2019-10-12T01-39-57Z


# crds:
# - 

configurations:
- ./kustom-config.yaml
