apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-c4m
spec:
  acme:
    email: admin@codeformuenster.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-c4m-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: changeme
