# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: nominatim
#   labels:
#     app.kubernetes.io/name: nominatim
#     app.kubernetes.io/component: api
# spec:
#   rules:
#   - host: nominatim.example.com
#     http:
#       paths:
#       - backend:
#           serviceName: nominatim
#           servicePort: api
#   tls:
#   - secretName: nominatim-tls
#     hosts:
#     - nominatim.example.com

# ---
# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Certificate
# metadata:
#   name: nominatim
#   labels:
#     app.kubernetes.io/name: nominatim
#     app.kubernetes.io/component: api
# spec:
#   secretName: nominatim-tls
#   commonName: nominatim.example.com
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt

---
apiVersion: v1
kind: Service
metadata:
  name: nominatim
  labels:
    app.kubernetes.io/name: nominatim
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: nominatim-geocoder
spec:
  ports:
  - name: api
    port: 8080
    targetPort: api
  selector:
    app.kubernetes.io/name: nominatim
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: nominatim-geocoder

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nominatim-api-configmap
  labels:
    app.kubernetes.io/name: nominatim
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: nominatim-geocoder
data:
  local.php: |
    <?php
     // Paths
     @define('CONST_Postgresql_Version', '11');
     @define('CONST_Postgis_Version', '2.5');
     // Website settings
     @define('CONST_Website_BaseURL', '/');
     @define('CONST_Replication_Url', 'http://download.geofabrik.de/europe/germany/nordrhein-westfalen/muenster-regbez-updates/');
     @define('CONST_Replication_MaxInterval', '86400');     // Process each update separately, osmosis cannot merge multiple updates
     @define('CONST_Replication_Update_Interval', '86400');  // How often upstream publishes diffs
     @define('CONST_Replication_Recheck_Interval', '900');   // How long to sleep if no update found yet
     @define('CONST_Pyosmium_Binary', '/usr/local/bin/pyosmium-get-changes');
     @define('CONST_Database_DSN', 'pgsql:host=postgis;port=5432;user=nominatim;password=n0mn0m;dbname=nominatim'); // <driver>:host=<host>;port=<port>;user=<username>;password=<password>;dbname=<database>
    ?>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-data
  labels:
    app.kubernetes.io/name: nominatim
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: nominatim-geocoder
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nominatim
  labels:
    app.kubernetes.io/name: nominatim
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: nominatim-geocoder
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nominatim
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: nominatim-geocoder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nominatim
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: nominatim-geocoder
    spec:
      volumes:
      - name: localphp
        configMap:
          name: nominatim-api-configmap
          items:
          - key: local.php
            path: local.php
      - name: data
        persistentVolumeClaim:
          claimName: nominatim-data
      initContainers:
      - name: init-db
        image: mediagis/nominatim:3.4
        # image: localhost:5000/nominatim:3.4
        volumeMounts:
        - name: data
          mountPath: /data
        - name: localphp
          mountPath: /app/src/build/settings/local.php
          subPath: local.php
        command:
        - /usr/bin/bash
        - -c
        args:
        - |
          set -e
          if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='nominatim'" )" != '1' ]; then
            echo -n "fetching pbf file from $PBF_URL"
            curl -s -C - -o /data/regbez-muenster.osm.pbf "$PBF_URL"
            echo -e "done\nstarting import"
            /app/src/build/utils/setup.php --osm-file /data/regbez-muenster.osm.pbf --all --threads 4
            rm -rf /data/regbez-muenster.osm.pbf
          else
            echo "skipping initialization"
          fi
        env:
        - name: PBF_URL
          value: http://download.geofabrik.de/europe/germany/nordrhein-westfalen/muenster-regbez-latest.osm.pbf
        - name: PGHOST
          value: postgis
        - name: PGUSER
          value: nominatim
      containers:
      - name: nominatim
        image: mediagis/nominatim:3.4
        # image: localhost:5000/nominatim:3.4
        command:
        - /usr/bin/bash
        - -c
        args:
        - |
          /usr/sbin/apache2ctl -D FOREGROUND
          tail -f /var/log/apache2/error.log
        env:
        - name: PGHOST
          value: postgis
        - name: PGUSER
          value: nominatim
        ports:
        - name: api
          containerPort: 8080
        volumeMounts:
        - name: localphp
          mountPath: /app/src/build/settings/local.php
          subPath: local.php
