# based on https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: postgis
  labels:
    app.kubernetes.io/name: postgis
    app.kubernetes.io/component: database
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgis
    app.kubernetes.io/component: database
    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgis
  labels:
    app.kubernetes.io/name: postgis
    app.kubernetes.io/component: database
spec:
  serviceName: postgis
  replicas: 1
  # selector:
  #   matchLabels:
  #     app.kubernetes.io/name: postgis
  #     app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgis
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: postgis
        image: codeformuenster/postgis-nominatim:0.1.0
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        env:
        # FIXME create random password in secret on commandline
        - name: POSTGRES_PASSWORD
          value: n0mn0m
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 60
  # FIXME needs openebs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      # storageClassName: high-performance-high-resilience
