# This is the install related config. It specifies the version of openebs
# components i.e. custom operators that gets installed. This config is
# used by maya-apiserver.
apiVersion: v1
kind: ConfigMap
metadata:
  name: maya-install-config
  namespace: openebs
data:
  install: |
    spec:
      install:
      - version: "0.7.0"
