##---
# Source: app-with-url/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traffics-shiny
  namespace: traffics-shiny
  labels:
    app: traffics-shiny
    chart: app-with-url-v0.1.0
spec:
  ports:
  - port: 3838
    protocol: TCP
  selector:
    app: traffics-shiny
