apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swms-busradar-gtfs-realtime
commonLabels:
  app.kubernetes.io/part-of: swms-busradar-gtfs-realtime

resources:
- ./swms-busradar-gtfs-realtime.yaml
- ./fileserver.yaml

images:
- name: quay.io/codeformuenster/swms-busradar-gtfs-realtime
  newTag: 0.3.1
- name: quay.io/codeformuenster/swms-busradar-gtfs-realtime-init
  newTag: 0.3.0
- name: abiosoft/caddy
  newTag: 1.0.3-no-stats
