apiVersion: apps/v1
kind: Deployment
metadata:
  name: swms-busradar-gtfs-realtime
  labels:
    app.kubernetes.io/name: swms-busradar-gtfs-realtime
    app.kubernetes.io/component: translator
    app.kubernetes.io/part-of: swms-busradar-gtfs-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: swms-busradar-gtfs-realtime
      app.kubernetes.io/component: translator
      app.kubernetes.io/part-of: swms-busradar-gtfs-realtime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swms-busradar-gtfs-realtime
        app.kubernetes.io/component: translator
        app.kubernetes.io/part-of: swms-busradar-gtfs-realtime
    spec:
      volumes:
      - name: static-feed-volume
        emptyDir: {}
      - name:
      initContainers:
      - name: swms-busradar-gtfs-realtime-init
        volumeMounts:
          - mountPath: /dumps
            name: static-feed-volume
      containers:
      - name: swms-busradar-gtfs-realtime
        image: quay.io/codeformuenster/swms-busradar-gtfs-realtime:0.2.0
