apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: nginx
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meine-stadt-transparent
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: mst.kube.vsh.codeformuenster.org
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mst.kube.vsh.codeformuenster.org
    secretName: meine-stadt-transparent-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/component: nginx
    spec:
      volumes:
      - name: static-files-volume
        emptyDir: {}
      - name: nginxconfig
        configMap:
          name: nginx-config
      initContainers:
      - name: copy-static
        image: konstin2/meine-stadt-transparent:v0.2.9
        command:
          - cp
          - -r
          - /static
          - /static-files
        volumeMounts:
        - mountPath: /static-files
          name: static-files-volume
      containers:
      - name: nginx
        image: nginx:1.20-alpine
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
        - mountPath: /static
          name: static-files-volume
          subPath: static
        - mountPath: /etc/nginx/conf.d/meine-stadt-transparent.conf
          name: nginxconfig
          subPath: nginx.conf
