apiVersion: batch/v1
kind: CronJob
metadata:
  name: update
  labels:
    app.kubernetes.io/name: update
    app.kubernetes.io/component: update
spec:
  schedule: "5 4 * * *"
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: dotenv
            configMap:
              name: meine-stadt-transparent-dot-env
          containers:
          - name: import-scraped-json
            image: konstin2/meine-stadt-transparent:v0.2.9
            imagePullPolicy: Always
            command:
            - /bin/bash
            - -c
            args:
            - 'set -e &&
              /app/.venv/bin/python /app/manage.py cron'
            volumeMounts:
            - name: dotenv
              mountPath: /app/.env
              subPath: .env
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: meine-stadt-transparent-secrets
                  key: database_url
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: meine-stadt-transparent-secrets
                  key: sentry_dsn
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: meine-stadt-transparent-secrets
                  key: secret_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secret-key
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: access-key
            - name: EMAIL_URL
              valueFrom:
                secretKeyRef:
                  name: meine-stadt-transparent-secrets
                  key: email_url
          imagePullSecrets:
          - name: regcred
