# https://docs.openebs.io/docs/next/ugcstor.html#creating-cStor-storage-pools

---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool
  # annotations:
    # https://docs.openebs.io/docs/next/ugcstor.html#setting-pool-policies
    # cas.openebs.io/config: |
    #   - name: PoolResourceRequests
    #     value: |-
    #         memory: 2Gi
    #   - name: PoolResourceLimits
    #     value: |-
    #         memory: 4Gi
    #   - name:  AuxResourceLimits
    #     value: |-
    #         memory: 0.5Gi
    #         cpu: 100m
    #   - name: AuxResourceRequests
    #     value: |-
    #         memory: 0.5Gi
    #         cpu: 100m
    #   openebs.io/cas-type: cstor
spec:
  name: cstor-disk-pool
  type: disk
  # maxPools: 3
  # minPools: 3
  poolSpec:
    poolType: striped
    # cacheFile: /var/openebs/sparse/sparse-claim-auto.cache
    # overProvisioning: false
  blockDevices:
    # kubectl -n openebs describe blockdevices
    # kubectl -n openebs get blockdevices
    # kubectl -n openebs get blockdevices -o name
    blockDeviceList:
    - blockdevice-7a8f643f80f28da689d2961833f91bda
    - blockdevice-86fc1ddbabee9f1522e2777c609b511b
    - blockdevice-c1d827a4691218ff02682cb5ef3e262f

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cstor-localssd-3x-nowait
  annotations:
    openebs.io/cas-type: cstor
    # cas.openebs.io/config: |
    #   - name: FSType
    #     value: ext4
    #   - name: TargetResourceLimits
    #     value: |-
    #         memory: 1Gi
    #         cpu: 100m
    #   - name: TargetResourceRequests
    #     value: |-
    #         memory: 1Gi
    #         cpu: 100m
    #   - name:  AuxResourceLimits
    #     value: |-
    #         memory: 0.5Gi
    #         cpu: 100m
    #   - name: AuxResourceRequests
    #     value: |-
    #         memory: 0.5Gi
    #         cpu: 100m
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-disk-pool"
      - name: ReplicaCount
        value: "3"
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cstor-localssd-1x-wait
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-disk-pool"
      - name: ReplicaCount
        value: "1"
      - name: TargetResourceLimits
        value: |-
            memory: 1Gi
            cpu: 100m
      - name: TargetResourceRequests
        value: |-
            memory: 1Gi
            cpu: 100m
      - name:  AuxResourceLimits
        value: |-
            memory: 0.5Gi
            cpu: 100m
      - name: AuxResourceRequests
        value: |-
            memory: 0.5Gi
            cpu: 100m
provisioner: openebs.io/provisioner-iscsi
volumeBindingMode: WaitForFirstConsumer