apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/codeformuenster/kustomized//openebs?ref=fac01a5

# resources:
# - ./cstor-storage.yaml

patchesStrategicMerge:
- ./openebs-operator_patches.yaml
