apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: c4m-muenster-update-production

resources:
- ../../../base/namespace-pss-restricted
- muenster-update-production.enc.yaml
- pgcluster.yaml
- sync.yaml
