apiVersion: v1
kind: Secret
metadata:
    name: backend-api
type: Opaque
stringData:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:LJs8NOEzZbUfs9FXAP2V5RxMKpGyCWE8QOLT4h6DZMUJXoCp9I+3VY1xUkhXrQ63xSY=,iv:vOvc8nIN6Whn2kA7jQUQueGmVKwKxn/SP3JjAZOfQpo=,tag:c7GvqQyFvmz42P+n7FEszA==,type:str]
    MUENSTERLAND_API_TOKEN: ENC[AES256_GCM,data:JG0j2YX5RROq8YuUNnywZwGj8VTd1rvVJ8d4oMxpy8U=,iv:KVjUCDZ/ayOtxOjPSWir/CZ0x6JnoJNoxysuVJrmLxM=,tag:scZC0RQhCmwQmZVQ4j7kzA==,type:str]
    DATENPORTAL_USER: ENC[AES256_GCM,data:L2Ue1ikNAdSqBtmP00I=,iv:PuxrIuX/Zt8g8ZFtgDkyMVgA98QleaTNlD5Tj0d//Fw=,tag:j/LubJ0ylfBP1b8+00dGmQ==,type:str]
    DATENPORTAL_PASSWORD: ENC[AES256_GCM,data:DJS4UnsXyj33,iv:rM7cPJsiOB6/yY3B/L1GLMMRqGlTv2Gfg39z68I4r/E=,tag:dONTVo8s2OUB4oy3ExYa8A==,type:str]
sops:
    age:
        - recipient: age1nzqaqzm7wfz04ld5esukhkghmayzt8xmnrjlau0rdcycjlu53pesgew089
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZnJaLzlBSXRUUzZPV09a
            MnhseW5WTW11YXhsTUlTMXdJZUhjbjk3dmdFCkd0RUpWWHNLYUlpZUd4MDBqRmRy
            ZDJaVy81a3JwbmhlN3ZRWWJUcmptcE0KLS0tIG5zbXpVKzM5ZTZnZzBEL056TVhl
            ZkRIRjlvaS9pOE5vRGVlTzRJZktsYlkKM7iQwix6GnITwp7E46DNc78cJOzvRRaF
            pdX3EeHyUHshcf7PlZTE1fu37PfgUhr5Z1pY7e8tW+FzoIT+nmylFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T14:19:37Z"
    mac: ENC[AES256_GCM,data:fGBmNpfv2sfl+UaDKPIgdRvh64JHLOM7TTJBsrUruBmoza/vJrJb1ENG5RlmZNQNt6vTYYHzYELjGYPdeufPes1rYANYLWmsnLj196u5vA/BPgJSnaadtXlrXkyXp9SgcWgt/OUWrn7OtsBrIU6S7a0FZIr1lE7CpjVDaXg2FoE=,iv:UUIDJXqPezKhtoSxDEfrELh9VsIMdDcJhO0239OyuiU=,tag:8h/ulwNvjKCQf6H+m5C+Dw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
