apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shared-test
commonLabels:
  app.kubernetes.io/part-of: kinto

bases:
- ../base

images:
- name: kinto/kinto-server
  newTag: 13.2.2

configMapGenerator:
- name: kinto
  files:
  - kinto.ini

secretGenerator:
- name: postgres
  env: ./secrets/postgres
- name: kinto
  env: ./secrets/kinto

patchesStrategicMerge:
- ingress-patches.yaml
