apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  storageClassName: high-performance-high-resilience
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20G
