apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  storageClassName: local-ssd-normal-resilience
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50G
