apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openebs
commonLabels:
  # app.kubernetes.io/name: openebs
  app.kubernetes.io/part-of: openebs

resources:
- openebs-operator.yaml
