apiVersion: v1
kind: Service
metadata:
  name: climatems
  namespace: climatems
  labels:
    app.kubernetes.io/name: climatems
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: climatems
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app.kubernetes.io/name: climatems
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: climatems

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: climatems-climatems
  namespace: climatems
automountServiceAccountToken: false

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: climatems
  namespace: climatems
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-c4m
  labels:
    app.kubernetes.io/name: climatems
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: climatems
spec:
  rules:
  - host: climatems.codeformuenster.org
    http:
      paths:
      - backend:
          service:
            name: climatems
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - climatems.codeformuenster.org
    secretName: climatems-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: climatems
  namespace: climatems
  labels:
    app.kubernetes.io/name: climatems
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: climatems
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: climatems
      app.kubernetes.io/component: webserver
      app.kubernetes.io/part-of: climatems
  template:
    metadata:
      labels:
        app.kubernetes.io/name: climatems
        app.kubernetes.io/component: webserver
        app.kubernetes.io/part-of: climatems
    spec:
      automountServiceAccountToken: false
      serviceAccountName: climatems-climatems
      containers:
      - name: climatems
        image: ghcr.io/codeformuenster/climatems:v0.1.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"