apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kinto
  labels:
    app.kubernetes.io/name: kinto
    app.kubernetes.io/component: datastore
spec:
  template:
    spec:
      containers:
      - name: kinto
        image: kinto/kinto-server:13.6.1
        env:
        - name: KINTO_STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: postgres-url
        - name: KINTO_PERMISSION_URL
          valueFrom:
            secretKeyRef:
              name: postgres
              key: postgres-url
