apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: verkehrsunfaelle

bases:
  - ../base
resources:
  - namespace.yaml
  - random-accident.yaml
  - postgres-backup.yaml
patchesStrategicMerge:
  - kinto-image_patch.yaml
  - kinto-pod_patch.yaml
  - kinto-config_patch.yaml
  - kinto-ingress_patch.yaml
  - postgres_patch.yaml
