apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: verkehrsunfaelle

bases:
  - ../base
resources:
  - namespace.yaml
  - editor-data-helpers.yaml
  - postgres-backup.yaml
patchesStrategicMerge:
  - kinto-pod_patch.yaml
  - kinto-config_patch.yaml
  - kinto-ingress_patch.yaml
  - postgres_patch.yaml

images:
- name: quay.io/codeformuenster/verkehrsunfaelle
  newTag: 2019-11-15
- name: quay.io/codeformuenster/postgres-minio-mc
  newTag: 0.2.0
