apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  template:
    spec:
      containers:
      - name: postgres
        image: quay.io/codeformuenster/verkehrsunfaelle:2019-09-03_editor-web
        env:
        - name: POSTGRES_USER
          value: null
          valueFrom:
            secretKeyRef:
              name: postgres
              key: username
        - name: POSTGRES_PASSWORD
          value: null
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
