apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kinto

# https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
commonLabels:
  app.kubernetes.io/part-of: kinto-stack

resources:
# - 0-namespace.yaml
# - cluster-role-oidc-mapping.yaml
- kinto.yaml
- postgres.yaml
# - elasticsearch.yaml
# - realm.yaml
