apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kinto
commonLabels:
  app.kubernetes.io/part-of: kinto-stack

resources:
- kinto.yaml
- postgres.yaml
# - elasticsearch.yaml

images:
- name: kinto/kinto-server
  newTag: 13.0.1

# configMapGenerator:
# - name: kinto
#   files:
#   - kinto.ini
