apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-clusterissuer
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  - clusterissuers
  verbs:
  - "create"
  - "delete"
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - "create"
  - "delete"
  - "get"
  - "patch"
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - cert-manager-clusterissuer
  verbs:
  - "use"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-clusterissuer
subjects:
  - kind: ServiceAccount
    name: cert-manager-clusterissuer
roleRef:
  kind: ClusterRole
  name: cert-manager-clusterissuer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cert-manager-clusterissuer
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'configMap'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-clusterissuer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager-clusterissuer
spec:
  template:
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: cert-manager-clusterissuer
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: cert-manager-clusterissuer
        image: "docker.io/giantswarm/docker-kubectl:latest"
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset

          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.

          kubectl apply -f /data/cluster-issuer.yaml 2>&1
        volumeMounts:
        - name: cert-manager-clusterissuer
          mountPath: /data/
        resources:
          requests:
            cpu: 50m
            memory: 75Mi
      volumes:
      - name: cert-manager-clusterissuer
        configMap:
          name: cert-manager-clusterissuer
      restartPolicy: Never
  backoffLimit: 10
