apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
- https://github.com/fluxcd/flux2/releases/download/v0.16.2/install.yaml

patches:
- path: ./zero-replicas-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: image-.*-controller
