apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow
commonLabels:
  app.kubernetes.io/part-of: airflow

resources:
# postgres
- ./helm/output/airflow/charts/postgresql/templates/configmap.yaml
- ./helm/output/airflow/charts/postgresql/templates/deployment.yaml
- ./helm/output/airflow/charts/postgresql/templates/pvc.yaml
- ./helm/output/airflow/charts/postgresql/templates/secrets.yaml
- ./helm/output/airflow/charts/postgresql/templates/svc.yaml

# redis
- ./helm/output/airflow/charts/redis/templates/configmap.yaml
- ./helm/output/airflow/charts/redis/templates/headless-svc.yaml
- ./helm/output/airflow/charts/redis/templates/health-configmap.yaml
- ./helm/output/airflow/charts/redis/templates/redis-master-statefulset.yaml
- ./helm/output/airflow/charts/redis/templates/redis-master-svc.yaml
- ./helm/output/airflow/charts/redis/templates/secret.yaml


# airflow
- ./helm/output/airflow/templates/configmap-env.yaml
- ./helm/output/airflow/templates/configmap-git-clone.yaml
- ./helm/output/airflow/templates/configmap-scripts.yaml
- ./helm/output/airflow/templates/deployments-flower.yaml
- ./helm/output/airflow/templates/deployments-scheduler.yaml
- ./helm/output/airflow/templates/deployments-web.yaml
- ./helm/output/airflow/templates/poddisruptionbudget.yaml
- ./helm/output/airflow/templates/role-binding.yaml
- ./helm/output/airflow/templates/role.yaml
- ./helm/output/airflow/templates/service-account.yaml
- ./helm/output/airflow/templates/service-flower.yaml
- ./helm/output/airflow/templates/service-web.yaml
- ./helm/output/airflow/templates/service-worker.yaml
- ./helm/output/airflow/templates/statefulsets-workers.yaml
- ./ingress.yaml

images:
# - name: docker.elastic.co/elasticsearch/elasticsearch-oss
#   newName: codeformuenster/elasticsearch-oss-plugins
#   newTag: "7.2.0-testing1"

# patchesStrategicMerge:
# - ./patches.yaml

configMapGenerator:
# - name: elasticsearch-master-config
#   behavior: replace
#   files:
#   - elasticsearch.yml=./config.yaml

# secretGenerator:
# - name: certificates-transport
#   files:
#   - root-ca.pem=./certs/root-ca.pem
#   - node.pem=./certs/node.pem
#   - node-key.pem=./certs/node-key.pem

