apiVersion: v1
kind: Secret
metadata:
  name: fathom-backup-s3-credentials
  namespace: fathom
  labels:
    app.kubernetes.io/name: fathom
type: Opaque
data:
  MC_HOST_c4m: aHR0cHM6Ly88QWNjZXNzIEtleT46PFNlY3JldCBLZXk+QDxZT1VSLVMzLUVORFBPSU5UPg==
