FROM quay.io/bitnami/minio-client:2021-debian-10

USER root

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-recommends install sqlite3=3.* && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY makebackup.sh /usr/local/bin/makebackup.sh

USER 1001

ENTRYPOINT ["/usr/local/bin/makebackup.sh"]
