---
apiVersion: v1
kind: Service
metadata:
  name: fathom
  namespace: fathom
  labels:
    app.kubernetes.io/name: fathom
spec:
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/name: fathom

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fathom
  namespace: fathom
  labels:
    app.kubernetes.io/name: fathom
spec:
  rules:
  - host: ct.codeformuenster.org
    http:
      paths:
      - path: /
        backend:
          serviceName: fathom
          servicePort: 8080
  tls:
  - hosts:
    - ct.codeformuenster.org
    secretName: fathom-tls

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fathom-tls
  namespace: fathom
  labels:
    app.kubernetes.io/name: fathom
spec:
  secretName: fathom-tls
  dnsNames:
    - ct.codeformuenster.org
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fathom-dot-env
  namespace: fathom
data:
  .env: |
    FATHOM_GZIP=true
    FATHOM_DEBUG=false
    FATHOM_DATABASE_DRIVER="sqlite3"
    FATHOM_DATABASE_NAME="/fathom-db/fathom.db"
    FATHOM_DATABASE_USER=""
    FATHOM_DATABASE_PASSWORD=""
    FATHOM_DATABASE_HOST=""
    FATHOM_DATABASE_SSLMODE=""
    FATHOM_SECRET="C2qF85BqaonNvzxomeDyOzv+4o5DfoLGw9Hs40wG2REoyg8EmUqADDM7013myiiX"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fathom-database-volume-claim
  namespace: fathom
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fathom
  namespace: fathom
  labels:
    app.kubernetes.io/name: fathom
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fathom
  spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fathom
    spec:
      containers:
      - name: fathom
        image: quay.io/codeformuenster/fathom:flopp-fathom-93caa1a
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: fathom-config
          mountPath: /app/.env
          subPath: .env
          readOnly: true
        - mountPath: /fathom-db
          name: fathom-database-volume
      volumes:
      - name: fathom-config
        configMap:
          name: fathom-dot-env
      - name: fathom-database-volume
        persistentVolumeClaim:
          claimName: fathom-database-volume-claim
