apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.containerPort }}
        path: /
  tls:
  - hosts:
    - {{ .Values.url }}
    secretName: {{ .Values.name }}-tls
