apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  ports:
  - port: {{ .Values.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Values.name }}
