apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: kibana
  labels:
    app: kibana
    stack: logging
data:
  kibana.yml: |
    elasticsearch.url: "http://elasticsearch.elasticsearch.svc:9200"
    server.host: "0"
