apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: kibana
  # annotations:
  #   flux.weave.works/automated: "true"
  #   flux.weave.works/tag.kibana: glob:6.2.*
  labels:
    app: kibana
    stack: logging
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
        stack: logging
    spec:
      # FIXME
      # healthcheck + resources
      containers:
      - name: kibana
        # image: docker.elastic.co/kibana/kibana-oss:6.2.4
        image: docker.elastic.co/kibana/kibana-oss:6.4.1
        # env:
        # - name: ELASTICSEARCH_PASSWORD
        #   value: changeme
        ports:
        - containerPort: 5601
        resources: {}
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: kibana
