# FIXME service to maya-exporter here
---
apiVersion: v1
kind: Service
metadata:
  name: maya-apiserver-service
  namespace: openebs
spec:
  ports:
  - name: exporter
    port: 5656
    protocol: TCP
    targetPort: 5656
  selector:
    name: maya-apiserver


---
# https://github.com/openebs/openebs/blob/master/k8s/openebs-servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: openebs
  name: openebs
  namespace: openebs
spec:
  endpoints:
  - path: /metrics
    port: exporter
  namespaceSelector:
    matchNames:
    - openebs
  selector:
    matchLabels:
      openebs.io/cas-type: cstor
      monitoring: volume_exporter_prometheus