---
# Source: loki-stack/charts/loki/templates/role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki
  labels:
    app: loki
    chart: loki-0.10.0
    heritage: Tiller
    release: loki
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [loki]

