apiVersion: v1
kind: Service
metadata:
  name: digitransit
spec:
  selector:
    app: digitransit
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit
  labels:
    app: digitransit
spec:
  # replicas: 8
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 0
  selector:
    matchLabels:
      app: digitransit
  template:
    metadata:
      labels:
        app: digitransit
    spec:
      containers:
      - name: digitransit
        image: codeformuenster/digitransit-ui
        # command: ["yarn", "run", "start"]
        command: ["/usr/local/bin/node", "server/server"]
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG
          value: cfm
        - name: LOCATIONIQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: locationiq
              key: access-token
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   periodSeconds: 5
        #   timeoutSeconds: 10
        #   failureThreshold: 2
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 150
        #   periodSeconds: 10
        #   timeoutSeconds: 10
        #   failureThreshold: 10
        # resources:
        #   requests:
        #     memory: "1536Mi"
        #     cpu: 600m
        #   limits:
        #     memory: "1536Mi"
        #     cpu: 2000m
        volumeMounts:
        - name: digitransit-cfm-config
          mountPath: /opt/digitransit-ui/app/configurations/config.cfm.js
          subPath: config.cfm.js
        - name: digitransit-cfm-config
          mountPath: /opt/digitransit-ui/app/configurations/config.default.js
          subPath: config.default.js
        - name: digitransit-cfm-config
          mountPath: /opt/digitransit-ui/sass/themes/cfm/main.scss
          subPath: main.scss
        - name: digitransit-cfm-config
          mountPath: /opt/digitransit-ui/sass/themes/cfm/_theme.scss
          subPath: _theme.scss
      volumes:
      - name: digitransit-cfm-config
        configMap:
          name: digitransit-cfm
