apiVersion: v1
kind: Service
metadata:
  name: digitransit
spec:
  selector:
    app: digitransit
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit
  labels:
    app: digitransit
spec:
  selector:
    matchLabels:
      app: digitransit
  template:
    metadata:
      labels:
        app: digitransit
    spec:
      containers:
      - name: digitransit
        # image: verschwoerhaus/digitransit-ui:1172406
        image: hsldevcom/digitransit-ui:ci-f62dbcf83f828ccbd6721b24ad4dabf9335e3407
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG
          # value: vsh
          value: cfm
        - name: OTP_URL
          # value: "https://api.digitransit.im.verschwoerhaus.de/routing/v1/routers/vsh/"
          value: "https://api.digitransit.codeformuenster.org/routing/v1/routers/cfm/"
        - name: GEOCODING_BASE_URL
          # value: "https://api.digitransit.im.verschwoerhaus.de/geocoding/v1"
          value: "https://api.digitransit.codeformuenster.org/geocoding/v1"
        - name: LOCATIONIQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: locationiq
              key: access-token
        volumeMounts:
        - name: digitransit-cfm-config
          mountPath: /opt/digitransit-ui/app/configurations/config.cfm.js
          subPath: config.cfm.js
      volumes:
      - name: digitransit-cfm-config
        configMap:
          name: digitransit-cfm