apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: digitransit
commonLabels:
  app.kubernetes.io/part-of: digitransit

resources:
- ./digitransit.yaml
- ./graphiql.yaml
- ./hsl-map-server.yaml
- ./opentripplanner.yaml
- ./photon-pelias.yaml
- ./ingress.yaml

# images:
# - name: verschwoerhaus/digitransit-proxy-vsh
#   newTag: 01671d2
# - name: verschwoerhaus/digitransit-ui
#   newTag: "1172406"
# - name: verschwoerhaus/graphiql
#   newTag: 2019-10-30
# - name: verschwoerhaus/hsl-map-server
#   newTag: b4adf23
# - name: verschwoerhaus/opentripplanner-data-container-vsh
#   newTag: 2019-10-28-latest
# - name: hsldevcom/opentripplanner
#   newTag: a0c7971f62251a3a1070652a3895c628557e1b62
# - name: stadtulm/photon-pelias-adapter
#   newTag: 5903fc0

secretGenerator:
- name: locationiq
  behavior: create
  envs:
  - ./secrets/locationiq.env

configMapGenerator:
- name: digitransit-cfm
  behavior: create
  files:
  - config.cfm.js=./digitransit-config-cfm.js
