apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: digitransit
commonLabels:
  app.kubernetes.io/part-of: digitransit

resources:
- ./digitransit.yaml
- ./graphiql.yaml
- ./hsl-map-server.yaml
- ./opentripplanner.yaml
- ./photon-pelias.yaml
- ./ingress.yaml

images:
# - name: verschwoerhaus/digitransit-proxy-vsh
#   newTag: 01671d2
- name: codeformuenster/digitransit-ui
  newTag: master-test3
- name: codeformuenster/digitransit-graphiql
  newTag: master@sha256:1bf841ff6012008e827b73c3354edb5576f6cfecf8534ca62a380e800bf278b6
- name: verschwoerhaus/hsl-map-server
  newTag: b4adf23
- name: codeformuenster/opentripplanner-graph
  newTag: 0.1.1
- name: stadtulm/photon-pelias-adapter
  newTag: 5903fc0

secretGenerator:
- name: locationiq
  behavior: create
  envs:
  - ./secrets/locationiq.env

configMapGenerator:
- name: digitransit-cfm
  behavior: create
  files:
  - config.cfm.js=./configs/config.cfm.js
  - config.default.js=./configs/config.default.js
  - main.scss=./configs/theme-cfm-main.scss
  - _theme.scss=./configs/theme-cfm.scss
- name: router-config
  behavior: create
  files:
  - router-config.json=./configs/router-config.json
