apiVersion: v1
kind: Service
metadata:
  name: opentripplanner
spec:
  selector:
    app: opentripplanner
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner
  labels:
    app: opentripplanner
spec:
  selector:
    matchLabels:
      app: opentripplanner
  template:
    metadata:
      labels:
        app: opentripplanner
    spec:
      containers:
      - name: opentripplanner
        image: codeformuenster/opentripplanner-graph:latest
        command: ["java", 
          "-Duser.timezone=Europe/Berlin", 
          "-jar", "/opt/opentripplanner/otp-shaded.jar", 
          "--server", 
          "--basePath", "./", 
          "--graphs", "./graphs", 
          "--router", "cfm"]

        # --basePath
        #   Set the path under which graphs, caches, etc. are stored by default.
        #   Default: /var/otp
        # --cache # pv?
        #   The directory under which to cache OSM and NED tiles. Default is
        #   BASE_PATH/cache.

        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /opt/opentripplanner/graphs/cfm/router-config.json
          subPath: router-config.json
      volumes:
      - name: config
        configMap:
          name: router-config

        # FIXME add readiness probe for:
        # 22:40:06.192 INFO (NetworkListener.java:755) Started listener bound to [0.0.0.0:8080]
        # 22:40:06.227 INFO (NetworkListener.java:755) Started listener bound to [0.0.0.0:8081]
        # 22:40:06.231 INFO (HttpServer.java:300) [HttpServer] Started.
        # 22:40:06.232 INFO (GrizzlyServer.java:154) Grizzly server running.
