apiVersion: v1
kind: Service
metadata:
  name: opentripplanner
spec:
  selector:
    app: opentripplanner
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner
  labels:
    app: opentripplanner
spec:
  selector:
    matchLabels:
      app: opentripplanner
  template:
    metadata:
      labels:
        app: opentripplanner
    spec:
      containers:
      - name: opentripplanner
        # image: hsldevcom/opentripplanner:a0c7971f62251a3a1070652a3895c628557e1b62
        image: codeformuenster/opentripplanner-graph:latest
        command: ["java", 
          "-Duser.timezone=Europe/Berlin", 
          "-jar", "/opt/opentripplanner/otp-shaded.jar", 
          "--server", 
          "--basePath", "./", 
          "--graphs", "./graphs", 
          "--router", "cfm"]
        ports:
        - containerPort: 8080
        
        # FIXME add readiness probe for:
        # 22:40:06.192 INFO (NetworkListener.java:755) Started listener bound to [0.0.0.0:8080]
        # 22:40:06.227 INFO (NetworkListener.java:755) Started listener bound to [0.0.0.0:8081]
        # 22:40:06.231 INFO (HttpServer.java:300) [HttpServer] Started.
        # 22:40:06.232 INFO (GrizzlyServer.java:154) Grizzly server running.
