apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak
commonLabels:
  app.kubernetes.io/part-of: keycloak

bases:
- github.com/codeformuenster/kustomized//keycloak

secretGenerator:
- name: keycloak-admin-user
  env: ./secrets/keycloak-password-secret
- name: postgres
  env: ./secrets/postgres-password-secret

patchesStrategicMerge:
- ./keycloak-ingress-patch.yaml
