name: 'check manifests'
on: pull_request

jobs:
  lint:
    name: "Lint kustomization"
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4

      - name: Build and validate kustomization
        uses: ubergesundheit/kube-check-action@main
        with:
          kustomize_build_input: sync
          kube-linter_flags: "--config .kube-linter.yaml"
          kubeconform_flags: "-strict -kubernetes-version 1.28.9 -schema-location 'https://raw.githubusercontent.com/ubergesundheit/kube-check-action/main/kubeconform-schemas/{{.ResourceKind}}.json' -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -schema-location default"
