name: 'check manifests'
on: pull_request

jobs:
  "lint '${{ matrix.directory }}'":
    name: "Lint '${{ matrix.directory }}' kustomization"
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
        directory:
        - sources/crashes
        - sources/traffics

    steps:
      - name: 'checkout'
        uses: actions/checkout@v3

      - name: Build and validate ${{ matrix.directory }} kustomizations
        uses: ubergesundheit/kube-check-action@v1.0.2
        with:
          kustomize_build_input: ${{ matrix.directory }}
          kube-linter_flags: "--config ${{ matrix.directory }}/.kube-linter.yaml"
          kubeconform_flags: "-strict -kubernetes-version 1.24.10"
