name: 'check manifests'
on: pull_request

jobs:
  check-crashes:
    name: 'lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: Build and validate crashes kustomizations
        uses: ubergesundheit/kube-check-action@v1.0.2
        with:
          kustomize_build_input: sources/crashes
          kubeconform_flags: "-strict -kubernetes-version 1.24.10"

  check-traffics:
    name: 'lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: Build and validate traffics kustomizations
        uses: ubergesundheit/kube-check-action@v1.0.2
        with:
          kustomize_build_input: sources/traffics
          kubeconform_flags: "-strict -kubernetes-version 1.24.10"
